# Site settings
author: Michael Fox
title: 
header-img: img/home-bg.png
email: michael.c.fox.ii@gmail.com
copyright_name: Michael Fox
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  micfoxii

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
